### ISSUE TITLE
No se guardan las reglas de vestimenta incompletas

### ISSUE THREAD

**Issue by faloi** [gobstones/gobstones-web#408]
# 🐞 Problema detectado

Si no se completa la cantidad de bolitas en alguna regla:

![image](https://user-images.githubusercontent.com/1585835/128233166-1744eccd-bad0-4da7-85e2-f2e3b926ede6.png)

y luego se guarda el proyecto, lo que sucede es que las reglas incompletas (en este caso, la primera) desaparecen:

```yaml
name: Pirulo
rules:
  - when:
      red: 0
      green: 0
      blue: 0
      black: 1
    image: PinClipart.com_weather-clipart-black-and_249191.png
    text: null
```

# :notebook: Acciones sugeridas

Ofrecer algún tipo de feedback visual para las reglas incompletas. Tal vez también tenga sentido bloquear la posibilidad de guardar una actividad con este error.
